### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Salbei2500** [AdlerSalbei/CO_Operation_Lions_Kiss_2.Enoch#1]
## Objectiv 1

- [x] Research Station mit Objekten ausstatten

- [x] Blufor Truppen dort verteilen

- [x] Independant Truppen organisieren

- [x] Zivilisten am Objectiv

- [x] Intel plazieren

- [x] Music Easter Egg

## Objectiv 2
- [x] Find Place

## Mission Flow
- [x] Callsigns

- [x] Intro bauen
- [x] Intro Music

- [x] Outro

## Loadouts & Equipment

- [x] Backpacks für Rifleman
- [x] Mehr Munition für Rifleman

- [x] Grendiere M32

- [x] LMG

- [x] AMG

## Tests 
- [x] Intro & Outro Locality

## Mods möglich
- [ ] LAMBS

## Final Stuff
- [x] Verify Loadout
